server:
    port: 8080

spring:
    profiles: dev

    datasource:
        dataSourceClassName: org.h2.jdbcx.JdbcDataSource
        url: jdbc:h2:mem:jhipster
        databaseName:
        serverName:
        username:
        password:

    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        database: H2
        openInView: false
        show_sql: true
        generate-ddl: false
        hibernate:
            ddl-auto: none
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
            hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

    mail:
        baseUrl: http://localhost:8080

    thymeleaf:
        mode: XHTML
        cache: false
        viewNames: error

metrics:
    jmx.enabled: true
    spark:
        enabled: true
        host: spark
        port: 9999
    graphite:
        enabled: false
        host: localhost
        port: 2003
        prefix: jhipster_sandbox

cache:
    timeToLiveSeconds: 3600
    ehcache:
        maxBytesLocalHeap: 16M
